### ISSUE TITLE
On manager dashboard edit user, look at page. It allow me to upload xls file with analyst credentials

### ISSUE THREAD

**Issue by mayureshEtouch** [mayureshEtouch/task-engine#30]
1. Open manager dashboard, click on user menu
2. Go to Edit any user
3. On edit user page look at page (It show me analyst page)
4. It has menu "Upload" menu with Analyst Login "Hi Analyst 1"
5. If I click on upload, 
   <img width="1299" alt="screen shot 2016-05-26 at 7 03 51 pm" src="https://cloud.githubusercontent.com/assets/16252075/15576263/a705ac4a-2374-11e6-8cfc-af6d04d513fb.png">

**Comment by mayureshEtouch** [comment]
<img width="1291" alt="screen shot 2016-05-26 at 7 05 05 pm" src="https://cloud.githubusercontent.com/assets/16252075/15576363/20bc72c6-2375-11e6-8db4-de10d8829f92.png">
Look at this. Manager also got task upload menu with analyst credentials

**Comment by Mukesh23singh** [comment]
Fixed
